vich_uploader:
    db_driver: orm

    mappings:
        coverMovie:
            uri_prefix: /uploads/movie/cover
            upload_destination: '%kernel.project_dir%/public/uploads/movie/cover/'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
